yellow/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^yellow/', include('yellow_app.urls',namespace='yellow')),
    
]

yellow_app/urls.py
from django.conf.urls import url
from .views import Register,ConfirmationEmailSent,EmailConfirm
from .views import SetPassword,Login





urlpatterns = [
    url(r'^register/$', Register.as_view(), name='register'),
    url(r'^confirmation-email-sent/$', ConfirmationEmailSent.as_view(), name='confirmation_email_sent'),
    url(r'^email-confirm/(?P<activation_code>\w+)/$', EmailConfirm.as_view(), name='email_confirm'),
    url(r'^set-password/$', SetPassword.as_view(), name='set_password'),
    url(r'^login/$', Login.as_view(), name='login'),
]

yellow_app/models.py
from django.db import models
from django.utils import timezone

#for key creation and activation
import hashlib
import random

#email sending
from django.core.mail import send_mail
from yellow.settings import DEFAULT_FROM_EMAIL


class Interest(models.Model): #why the user is using our service
    name=models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
    
    
class YellowUser(models.Model):
    email_address=models.EmailField(unique=True)
    full_name=models.CharField(max_length=100)
    gender=models.CharField(max_length=1,choices=(('M','Male'),('F','Female'),))
    date_of_birth=models.DateField()
    password=models.CharField(max_length=20,blank=True,null=True)
    is_verified=models.BooleanField(default=False)
    interests=models.ManyToManyField(Interest)
    
    date_created=models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.full_name
    
    @classmethod
    def set_password(cls,email_address,password):
        return cls.objects.filter(email_address=email_address).update(password=password)
    
    
    
class AccountConfirmation(models.Model):
    yellow_user=models.ForeignKey(YellowUser)
    activation_code=models.CharField(max_length=100)
    is_used=models.BooleanField(default=False)
    
    date_created=models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.activateion_code
    
    
    @classmethod
    def create(cls,user):
        #create confirmation code
        salt=hashlib.sha1(str(random.random()).encode('utf-8')).hexdigest()[:5]
        activation_code=hashlib.sha1((salt+user.email_address).encode('utf-8')).hexdigest()
        return cls.objects.create(yellow_user=user,activation_code=activation_code)
            
    
    def send_confirmation_mail(self,user):
        email_subject='Account Confirmtion'
        email_body='Thank you %s .Please click this link http://localhost:8000/yellow/email-confirm/%s \
                   to activate your account.'%(user.full_name,self.activation_code)
        send_mail(email_subject,email_body,DEFAULT_FROM_EMAIL,[user.email_address])
     
     
    @classmethod   
    def confirm_email(cls,activation_code):
        try:
            ac=cls.objects.get(activation_code=activation_code,is_used=False)
            ac.is_used=True
            ac.save()
            return ac
        except:
            return None
        
            
        
            

        
       
        
    
    
    
    
    
    
    
    

yellow_app/forms.py
from .models import AccountConfirmation
from .models import YellowUser

from django import forms

class RegisterForm(forms.ModelForm):
    class Meta:
        model=YellowUser
        exclude=['password','is_verified','date_created']
        

class SetPasswordForm(forms.Form):
    password=forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())
    
    def clean(self): 
        data=self.cleaned_data
        
        if data['password'] != data['confirm_password']:
            self._errors['password']=['Passwords Do not Match']
            del data['password']
        return data

class LoginForm(forms.Form):
    email_address=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput())
    

yellow_app/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.contrib import messages
from django.http import HttpResponseRedirect

from .forms import RegisterForm,SetPasswordForm,LoginForm

from .models import AccountConfirmation,YellowUser

from .models import YellowUser 



class Register(View):
    template_name='yellow_app/register.html'
    form=RegisterForm()
    
    def get(self,request,*args,**kwargs):
        return render(request,self.template_name,{'form':self.form})
    
    def post(self,request,*args,**kwargs):
        self.form=RegisterForm(request.POST)
        if self.form.is_valid():
            yellow_user=self.form.save()
            ac=AccountConfirmation.create(yellow_user)
            ac.send_confirmation_mail(yellow_user)
            messages.add_message(request,messages.INFO,'We have Sent you a confirmation email. ')
            return HttpResponseRedirect(reverse('yellow:confirmation_email_sent'))
        return render(request,self.template_name,{'form':self.form})
    
        

class ConfirmationEmailSent(View):
    template_name='yellow_app/confirm_email_sent.html'
    def get(self,request,*args,**kwargs):
        return render(request,self.template_name)
    
class EmailConfirm(View):
    template_name='yellow_app/email_confirm.html'
    def get(self,request,*args,**kwargs):
        email_confirmed=AccountConfirmation.confirm_email(self.kwargs['activation_code'])
        if email_confirmed:
            #set email in session
            request.session['email']=email_confirmed.yellow_user.email_address
            return HttpResponseRedirect(reverse('yellow:set_password'))
        else:
            messages.add_message(request,messages.INFO,'Confirmation Email Code is Invalid')
        return render(request,self.template_name)
    
    
    
class SetPassword(View):
    template_name='yellow_app/set_password.html'
    form=SetPasswordForm()
    
    def get(self,request,*args,**kwargs):
        return render(request,self.template_name,{'form':self.form})
    
    def post(self,request,*args,**kwargs):
        self.form=SetPasswordForm(request.POST)
        if self.form.is_valid():
            email_address=request.session['email']
            password_set=YellowUser.set_password(email_address,
                                                 self.form.cleaned_data['password'])
            if password_set:
                return HttpResponseRedirect(reverse('yellow:login'))
            else:
                messages.add_message(request,messages.INFO,'Setting Password Failed')
        return render(request,self.template_name,{'form':self.form})
    
  
class Login(View):
    template_name='yellow_app/login.html'
    form=LoginForm()
    
    def get(self,request,*args,**kwargs):
        return render(request,self.template_name,{'form':self.form})
    
    def post(self,request,*args,**kwargs):
        self.form=LoginForm(request.POST)
        if self.form.is_valid():
            print ("logged in")
        return render(request,self.template_name,{'form':self.form})
    
    

    

yellow_app/templates/yellow_app/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  
    <!-- bootstrap -->
    <link href="{% static 'bootstrap-3.3.4/css/bootstrap.min.css' %}" rel="stylesheet">
    
    
        <title>Yellow App | {% block title %}Home {% endblock %}</title>
    </head>
    
    <body>
        {% block page %}
        
         <div class="container"><!-- messages -->
             <div class="row-fluid">
                <div class="col-md-6 col-md-offset-3">
        {% block messages %}
        {% for m in messages %}
         {{m}}
        {% endfor %}
        {% endblock messages %}
                </div>
             </div>
         </div><!--/messages container-->
         
        <div class="container"><!-- content -->
            <div class="row-fluid">
                <div class="col-md-8 col-md-offset-2">
               {% block content %}
                
               {% endblock content %}
                </div>
            </div>
        </div><!--/ content container -->
        
        
        {% endblock page %}
    </body>
</html>

yellow_app/templates/yellow_app/confirm_email_sent.html
{% extends "yellow_app/base.html" %}

yellow_app/templates/yellow_app/email_confirm.html
{% extends 'yellow_app/base.html' %}

yellow_app/templates/yellow_app/login.html
{% extends 'yellow_app/base.html' %}

{% load bootstrap3 %}

{% block content %}
 
 <h3>Login</h3>
  <form action="{% url 'yellow:login' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary btn-block ">Log In</button>
  </form>
  


{% endblock %}

yellow_app/templates/yellow_app/register.html
{% extends 'yellow_app/base.html' %}

{% load bootstrap3 %}

{% block content %}

<h3>Register</h3>

<form class="form" method="post" action="{% url 'yellow:register' %}">
    {% csrf_token %}
 {% bootstrap_form form %}
 <button type="submit" class="btn btn-primary btn-block">Save</button>
</form>

{% endblock %}

yellow_app/templates/yellow_app/set_password.html
{% extends 'yellow_app/base.html' %}

{% load bootstrap3 %}

{% block content %}
 
 <h3>Password Set</h3>
  <form action="{% url 'yellow:set_password' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary btn-block ">Save</button>
  </form>
  


{% endblock %}